apiVersion: v1
kind: Secret
metadata:
  name: veloz-secrets
  namespace: loja-veloz
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "velozpassword123"
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
  DATABASE_URL: "postgres://postgres:velozpassword123@postgres-service.loja-veloz.svc.cluster.local:5432/pedidos_db"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service.loja-veloz.svc.cluster.local:5672"
  